#!/usr/bin/env bash
set -euo pipefail

TOR_SOCKS_PORT="${TOR_SOCKS_PORT:-9050}"
TOR_DATA_DIR="${TOR_DATA_DIR:-/tmp/tor-ephemeral}"
TOR_PID_FILE="${TOR_PID_FILE:-/tmp/tor-ephemeral.pid}"
# If the caller pointed us at an explicit proxychains config, honor it verbatim.
# Otherwise we generate a runtime config (see ensure_proxychains_conf) bound to
# the SAME port tor actually listens on, so proxychains does not fall back to the
# system-wide /etc/proxychains4.conf that hardcodes 9050 and thus ignores
# TOR_SOCKS_PORT entirely.
USER_PROXYCHAINS_CONF="${PROXYCHAINS_CONF:-}"
PROXYCHAINS_RUNTIME_CONF="${PROXYCHAINS_RUNTIME_CONF:-$TOR_DATA_DIR/proxychains-runtime.conf}"

log() { printf '[tor-ephemeral] %s\n' "$*" >&2; }

# Resolve the proxychains config to use, generating one pinned to
# $TOR_SOCKS_PORT when the caller has not supplied an explicit config. Prints the
# path on stdout.
ensure_proxychains_conf() {
  if [ -n "$USER_PROXYCHAINS_CONF" ]; then
    printf '%s' "$USER_PROXYCHAINS_CONF"
    return 0
  fi
  mkdir -p "$(dirname "$PROXYCHAINS_RUNTIME_CONF")"
  cat > "$PROXYCHAINS_RUNTIME_CONF" <<EOF
# Auto-generated by tor-ephemeral.sh — do not edit; regenerated on each run.
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 127.0.0.1 $TOR_SOCKS_PORT
EOF
  printf '%s' "$PROXYCHAINS_RUNTIME_CONF"
}

# Run a command through proxychains4 with the port-correct config forced via -f,
# so requests always target $TOR_SOCKS_PORT instead of the system default.
run_proxychains() {
  local conf
  conf=$(ensure_proxychains_conf)
  proxychains4 -f "$conf" "$@"
}

install_tor() {
  if command -v tor &>/dev/null && command -v proxychains4 &>/dev/null; then
    log "tor and proxychains4 binaries found"
    return 0
  fi
  
  log "WARNING: tor or proxychains4 not found."
  log "Automatic package installation is disabled. Proceeding without attempting to install."
  return 1
}

start_ephemeral() {
  # Check if a global Tor service is already listening and working on the specified port
  if run_proxychains -q curl -s --max-time 10 https://check.torproject.org/api/ip 2>/dev/null | grep -qi '"IsTor":\s*true'; then
    log "System Tor is already active on port $TOR_SOCKS_PORT. Using global service."
    return 0
  fi

  if [ -f "$TOR_PID_FILE" ]; then
    local existing_pid
    existing_pid=$(cat "$TOR_PID_FILE" 2>/dev/null || true)
    if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
      if grep -q "Bootstrapped 100%" "$TOR_DATA_DIR/tor.log" 2>/dev/null; then
        log "reusing active tor circuit (pid=$existing_pid) on socks5://localhost:$TOR_SOCKS_PORT"
        return 0
      fi
      log "tor process $existing_pid is still bootstrapping; waiting for the existing circuit"
      wait_for_bootstrap
      return $?
    fi
    rm -f "$TOR_PID_FILE"
  fi

  mkdir -p "$TOR_DATA_DIR"
  nohup tor --SocksPort "$TOR_SOCKS_PORT" \
     --DataDirectory "$TOR_DATA_DIR" \
     --Log "notice file $TOR_DATA_DIR/tor.log" \
     --RunAsDaemon 0 \
     --PidFile "$TOR_PID_FILE" \
     > "$TOR_DATA_DIR/nohup.out" 2>&1 &
  local tor_pid=$!
  echo "$tor_pid" > "$TOR_PID_FILE"
  log "tor starting (pid=$tor_pid)..."
  wait_for_bootstrap
}

wait_for_bootstrap() {
  local attempts=0
  while [ $attempts -lt 30 ]; do
    sleep 1
    if grep -q "Bootstrapped 100%" "$TOR_DATA_DIR/tor.log" 2>/dev/null; then
      log "tor circuit established on socks5://localhost:$TOR_SOCKS_PORT"
      log "use: proxychains4 -f $(ensure_proxychains_conf) <command>  (ALL_PROXY is deliberately NOT set)"
      return 0
    fi
    attempts=$((attempts + 1))
  done
  log "ERROR: tor bootstrap did not complete after 30s"
  return 1
}

check_ip() {
  log "verifying exit IP through Tor..."
  local ip
  ip=$(run_proxychains -q curl -s --max-time 15 https://check.torproject.org/api/ip 2>/dev/null || true)
  if echo "$ip" | grep -qi '"IsTor":\s*true'; then
    log "confirmed: traffic is routed through Tor"
  else
    log "WARNING: could not confirm Tor exit. Check result: ${ip:-timeout}"
  fi
}

stop_ephemeral() {
  relax_enforcement 2>/dev/null || true
  # Kill by PID file first
  if [ -f "$TOR_PID_FILE" ]; then
    local pid
    pid=$(cat "$TOR_PID_FILE" 2>/dev/null || true)
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      log "tor process $pid killed (via PID file)"
    fi
    rm -f "$TOR_PID_FILE"
  fi
  # Kill only orphans we can positively attribute to THIS ephemeral instance.
  # Match the exact "--DataDirectory <dir>" argument signature (a unique path)
  # rather than a broad "tor.*PORT" regex that can match unrelated processes.
  local orphan
  for orphan in $(pgrep -f -- "--DataDirectory $TOR_DATA_DIR" 2>/dev/null || true); do
    if [ "$orphan" != "$$" ]; then
      kill "$orphan" 2>/dev/null || true
      log "orphaned tor process $orphan killed (via data-dir match)"
    fi
  done
  rm -rf "$TOR_DATA_DIR" 2>/dev/null || true
  log "tor data directory removed"
  unset ALL_PROXY HTTP_PROXY HTTPS_PROXY
}

purge_tor() {
  relax_enforcement 2>/dev/null || true
  log "purging tor package..."
  log "Automatic package removal is disabled."
}

CHAIN="PROTEUS_TOR_ENFORCE"

# Resolve the uid that the tor process runs as, so enforcement can allow tor's
# own outbound traffic (new circuits, any protocol) while dropping everything
# else. Priority: explicit override -> running tor PID owner -> known service
# users. Prints nothing if it cannot be resolved.
resolve_tor_uid() {
  if [ -n "${TOR_UID:-}" ]; then
    printf '%s' "$TOR_UID"
    return 0
  fi
  if [ -f "$TOR_PID_FILE" ]; then
    local pid uid
    pid=$(cat "$TOR_PID_FILE" 2>/dev/null || true)
    if [ -n "$pid" ] && [ -e "/proc/$pid" ]; then
      uid=$(stat -c '%u' "/proc/$pid" 2>/dev/null || true)
      if [ -n "$uid" ]; then
        printf '%s' "$uid"
        return 0
      fi
    fi
  fi
  local candidate
  for candidate in debian-tor tor; do
    if uid=$(id -u "$candidate" 2>/dev/null); then
      printf '%s' "$uid"
      return 0
    fi
  done
  return 1
}

# Build DROP-by-default egress rules on the given iptables/ip6tables binary.
# Everything except loopback, tor's own traffic, and already-established flows
# is dropped — including UDP (so DNS cannot leak outside Tor).
apply_enforcement_rules() {
  local ipt="$1"
  local tor_uid="$2"
  sudo "$ipt" -D OUTPUT -j "$CHAIN" 2>/dev/null || true
  sudo "$ipt" -F "$CHAIN" 2>/dev/null || true
  sudo "$ipt" -X "$CHAIN" 2>/dev/null || true
  sudo "$ipt" -N "$CHAIN"
  # Allow loopback unconditionally (proxychains -> local tor SOCKS).
  sudo "$ipt" -A "$CHAIN" -o lo -j ACCEPT
  # Allow already-established/related flows so live circuits survive.
  sudo "$ipt" -A "$CHAIN" -m state --state ESTABLISHED,RELATED -j ACCEPT
  # Allow the tor process itself to open NEW outbound connections (any proto).
  if [ -n "$tor_uid" ]; then
    sudo "$ipt" -A "$CHAIN" -m owner --uid-owner "$tor_uid" -j ACCEPT
  fi
  # Drop everything else new going to external networks: TCP *and* UDP.
  # This is what stops direct HTTP, curl/webfetch, and plaintext DNS leaks.
  sudo "$ipt" -A "$CHAIN" -j DROP
  # Insert as first OUTPUT rule.
  sudo "$ipt" -I OUTPUT 1 -j "$CHAIN"
}

# Confirm Tor is actually carrying traffic before we DROP everything else.
# Returns 0 only when a proxychained request comes back as a Tor exit.
tor_is_working() {
  run_proxychains -q curl -s --max-time 15 https://check.torproject.org/api/ip 2>/dev/null \
    | grep -qi '"IsTor":\s*true'
}

enforce_kernel() {
  require_root "enforce" || return 1

  # SAFETY GATE 1: refuse to lock the machine down unless we can allow tor's own
  # egress. Applying a DROP-all rule without an --uid-owner ACCEPT for tor drops
  # tor's NEW circuit connections too, leaving the host with no internet AND no
  # working Tor — the exact "machine unusable" failure. Abort instead.
  local tor_uid
  tor_uid=$(resolve_tor_uid || true)
  if [ -z "$tor_uid" ]; then
    log "ABORT: cannot resolve the tor uid, so a kernel DROP-all would also block"
    log "       tor's own circuits and cut the host off entirely. Start tor first"
    log "       (bootstrap) or set TOR_UID=<uid>, then re-run enforce. No rules"
    log "       were applied; host networking is untouched."
    return 1
  fi

  # SAFETY GATE 2: tor must already be carrying traffic. Locking down before tor
  # works would brick the host until someone runs relax.
  if ! tor_is_working; then
    log "ABORT: tor is not confirmed working (no Tor exit on port $TOR_SOCKS_PORT)."
    log "       Run 'bootstrap' and wait for a circuit before enforce, so the"
    log "       lockdown never cuts the host off. No rules were applied."
    return 1
  fi

  log "tor traffic will be allowed by owner uid=$tor_uid"
  apply_enforcement_rules iptables "$tor_uid"
  log "iptables (IPv4) enforcement ON — all non-Tor outbound TCP/UDP is DROPped"

  # IPv6 must be locked down too, otherwise dual-stack hosts leak around IPv4.
  if command -v ip6tables &>/dev/null; then
    apply_enforcement_rules ip6tables "$tor_uid"
    log "ip6tables (IPv6) enforcement ON — non-Tor outbound IPv6 is DROPped"
  else
    # No ip6tables tooling: at least try to disable IPv6 egress via sysctl so it
    # cannot bypass the IPv4 rules. Best-effort; logged either way.
    if sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1 \
       && sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null 2>&1; then
      log "ip6tables missing — IPv6 disabled via sysctl to prevent leaks"
    else
      log "WARNING: ip6tables missing and IPv6 could not be disabled — IPv6 may leak"
    fi
  fi

  # SAFETY GATE 3: verify the host still reaches the internet *through Tor* after
  # the rules are live. If the lockdown killed connectivity (e.g. tor's uid does
  # not match the running circuit, or DNS now leaks and is dropped), auto-relax
  # so the machine is never left offline. Fail closed on the rules, open on the
  # host: an unusable machine is worse than a missing lockdown.
  if tor_is_working; then
    log "verified: host still reaches the internet through Tor under enforcement"
    log "  (webfetch, direct curl, plaintext DNS, and host-level HTTP will fail)"
  else
    log "ERROR: connectivity through Tor broke after enforcement was applied."
    log "       Rolling the rules back automatically so the host is not left"
    log "       offline. Investigate tor uid / DNS before retrying enforce."
    relax_enforcement || log "WARNING: auto-relax failed — run 'sudo $0 relax' now"
    return 1
  fi
}

relax_enforcement() {
  require_root "relax" || return 1
  sudo iptables -D OUTPUT -j "$CHAIN" 2>/dev/null || true
  sudo iptables -F "$CHAIN" 2>/dev/null || true
  sudo iptables -X "$CHAIN" 2>/dev/null || true
  if command -v ip6tables &>/dev/null; then
    sudo ip6tables -D OUTPUT -j "$CHAIN" 2>/dev/null || true
    sudo ip6tables -F "$CHAIN" 2>/dev/null || true
    sudo ip6tables -X "$CHAIN" 2>/dev/null || true
  else
    # Mirror of the sysctl fallback in enforce_kernel: re-enable IPv6 egress.
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1 || true
    sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0 >/dev/null 2>&1 || true
  fi
  log "iptables/ip6tables enforcement OFF — outbound traffic unrestricted"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    log "ERROR: '$1' requires root (iptables). Use sudo."
    return 1
  fi
}

bootstrap() {
  install_tor && start_ephemeral
}

teardown() {
  stop_ephemeral
}

full_teardown() {
  stop_ephemeral
  purge_tor
}

case "${1:-}" in
  bootstrap) bootstrap ;;
  start)     start_ephemeral ;;
  stop)      teardown ;;
  purge)     full_teardown ;;
  check)     check_ip ;;
  enforce)   enforce_kernel ;;
  relax)     relax_enforcement ;;
  *)
    echo "Usage: $0 {bootstrap|start|stop|purge|check|enforce|relax}"
    echo ""
    echo "  bootstrap  install tor if missing and start ephemeral circuit"
    echo "  start      start ephemeral tor (assumes binary exists)"
    echo "  stop       kill tor process and delete temp data directory"
    echo "  purge      stop + remove tor and proxychains packages from system"
    echo "  check      verify exit IP is routed through Tor"
    echo "  enforce    DROP all non-Tor outbound TCP/UDP over IPv4 and IPv6"
    echo "             (kernel-level lockdown; set TOR_UID=<uid> if tor runs"
    echo "             under a user this script cannot auto-detect)"
    echo "  relax      remove iptables/ip6tables enforcement rules"
    exit 1
    ;;
esac
